### ISSUE TITLE
Icons for the notice should be bigger on mobile 

### ISSUE THREAD

**Issue by spiii** [weg-li/weg-li#470] opened 2021-09-28 12:52 UTC
![Screenshot_20210928-144940.png](https://user-images.githubusercontent.com/7548931/135090271-320d049a-2cd2-4a92-ae1b-f6bf8b1162cc.png)

It is very difficult to use them in the mobile screen.
It would be an easy solution to resize them a bit.

**Comment by phoet** [comment] 2022-01-12 18:43
duplicate of #409

**Closed by phoet** 2022-01-12 18:43 UTC
